### PR TITLE
Allow tests to run on Rubinius

### PR DESCRIPTION
**Pull request by searls**
This PR follows @paddor's work in #17 to add my own pass of changes before merging.

I'm threading the needle pretty carefully here, but here's the gist/goal of how I want this merged in:
- [x] Run tests under rbx such that they only blow up if the test fails
- [x] warn users that natural assertions aren't going to work correctly under rbx
- [x] default natural assertions to enabled for all users, regardless of ripper support
- [x] make rspec given's own build work under rbx by re-implementing `NaturalAsserrtionControl` and skipping tests that are effectively verifying given's own natural assertion messages
- [x] get rbx into travis with a green build
- [x] remove public `Given.ok_to_use_natural_assertions`
- [x] do a minor version bump when released

All told, this PR doesn't acknowledge that we're explicitly supporting Rubinius, because we can't claim that without Ripper, but we can at least allow rspec-given users to throw rbx into their CI matrix without blowing them up. This is roughly the level of tenuous support RSpec itself has for rbx (so long as you don't use rspec-mocks).

### CODE REVIEW

**Comment by searls** [comment]
Just found an issue. It looks like the behavior of empty `Then{}` blocks differs between rbx & not.

under rbx 3.5:

```

  1) false   Then { }
     Failure/Error: Then { }
       Then expression failed at /Users/justin/code/rspec-given/rspec-given/spec/lib/given/natural_assertion_spec.rb:11
       Failing expression (possibly truncated): Then { }
     # ./lib/given/rspec/framework.rb:24:in `fail_with'
     # ./lib/given/module_methods.rb:42:in `fail_with'
     # ./lib/given/extensions.rb:127:in `_gvn_naturally_assert'
     # ./lib/given/extensions.rb:118:in `_gvn_evaluate'
     # ./lib/given/extensions.rb:102:in `_gvn_then'
     # ./spec/lib/given/natural_assertion_spec.rb:11:in `Then'
     # kernel/common/eval.rb:46:in `instance_eval'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/proc.rb:20:in `call'
     # kernel/loader.rb:732:in `run_at_exits'
     # kernel/loader.rb:762:in `epilogue'
     # kernel/loader.rb:877:in `main'
```

under mri 2.2.0, there is no failure.

**Comment by searls** [comment]
I don't want to get into this so I just added to the warning in 0aacc2f8720b1893de343101d5fab86e98528b2b

**Comment by searls** [comment]
(ignore the above status checks, i killed duplicative builds to save time on travis. build i'm watching is here: https://travis-ci.org/rspec-given/rspec-given/builds/102391760 )

**Comment by paddor** [comment]
Thanks so much for your effort.

**Comment by searls** [comment]
Had to hand-merge this. It's in.

**Comment by paddor** [comment]
Great! It works perfectly! I hope my PR wasn't too much off. :sweat_smile: 
Thanks again.

**Pull request closed without merging**
